--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.3.932
--   Created On : martes, 05 junio, 2012 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 

-- Create schema

USE [GD1C2012]
GO
/****** Object:  Schema [gd_esquema]    Script Date: 04/15/2012 01:58:54 ******/
CREATE SCHEMA [FEMIG] AUTHORIZATION [gd]
GO


--  Create Tables 
CREATE TABLE GD1C2012.FEMIG.Pantalla ( 
	pantallaID varchar(255) NOT NULL,
	descripcion varchar(255) NOT NULL
)
;

CREATE TABLE GD1C2012.FEMIG.Rol ( 
	rolID varchar(20) NOT NULL,
	descripcion varchar(50) NOT NULL,
	anulado varchar(1)    --  0: El rol está activo 1: El rol esta inhabilitado 
)
;

CREATE TABLE GD1C2012.FEMIG.RolPantalla ( 
	rolID varchar(20) NOT NULL,
	pantallaID varchar(255) NOT NULL,
	acceso varchar(1)    --  0 o null: no tiene acceso 1: tiene acceso 
)
;

CREATE TABLE GD1C2012.FEMIG.RolUsuario ( 
	usuarioID varchar(20) NOT NULL,
	rolID varchar(20) NOT NULL
)
;

CREATE TABLE GD1C2012.FEMIG.Usuario ( 
	usuarioID varchar(20) NOT NULL,
	nombre varchar(50) NOT NULL,
	apellido varchar(50) NOT NULL,
	email varchar(100),
	password varchar(50) NOT NULL,
	cantIntentosFallo numeric(18),
	cantMaxIntentos numeric(18),
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.Autos ( 
	patente varchar(10) NOT NULL,
	marca varchar(255) NOT NULL,
	modelo varchar(255) NOT NULL,
	licencia varchar(26) NOT NULL,
	rodado varchar(10) NOT NULL,
	nroSerieReloj varchar(18) NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.Chofer ( 
	dniChofer numeric(18) NOT NULL,
	nombre varchar(255) NOT NULL,
	apellido varchar(255) NOT NULL,
	direccion varchar(255) NOT NULL,
	telefono numeric(18) NOT NULL,
	email varchar(50),
	fechaNacimiento datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.ChoferAutoTurno ( 
	fecha datetime NOT NULL,
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL,
	patente varchar(10)
)
;

CREATE TABLE GD1C2012.FEMIG.Cliente ( 
	dniCliente numeric(18) NOT NULL,
	nombre varchar(255) NOT NULL,
	apellido varchar(255) NOT NULL,
	telefono numeric(18) NOT NULL,
	direccion varchar(255) NOT NULL,
	email varchar(255),
	fechaNacimiento datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.Factura ( 
	codFactura numeric(18) NOT NULL,
	fecha_inicio datetime NOT NULL,
	fecha_fin datetime NOT NULL,
	dniCliente numeric(18) NOT NULL,
	importe_total numeric(18) NOT NULL
)
;

CREATE TABLE GD1C2012.FEMIG.Reloj ( 
	nroSerieReloj varchar(18) NOT NULL,
	marca varchar(255) NOT NULL,
	modelo varchar(255) NOT NULL,
	fechaVersion datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.Rendicion ( 
	fecha datetime NOT NULL,
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL
)
;

CREATE TABLE GD1C2012.FEMIG.Turno ( 
	turnoID varchar(20) NOT NULL,
	horaInicio numeric(18) NOT NULL,
	horaFin numeric(18) NOT NULL,
	descripcion varchar(255) NOT NULL,
	valorFicha numeric(18,2) NOT NULL,
	valorBandera numeric(18,2) NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE GD1C2012.FEMIG.Viaje ( 
	viajeID numeric(18) NOT NULL,
	tipoViaje varchar(10) NOT NULL,
	cantFichas numeric(18) NOT NULL,
	fecha datetime NOT NULL,
	dniCliente numeric(18) NOT NULL,
	codFactura numeric(18),
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL
)
;


--  Create Indexes 
ALTER TABLE GD1C2012.FEMIG.Autos
	ADD CONSTRAINT UQ_Auto_licencia UNIQUE (licencia)
;

ALTER TABLE GD1C2012.FEMIG.Autos
	ADD CONSTRAINT UQ_Auto_nroSerieReloj UNIQUE (nroSerieReloj)
;

ALTER TABLE GD1C2012.FEMIG.Chofer
	ADD CONSTRAINT UQ_Chofer_email UNIQUE (email)
;

ALTER TABLE GD1C2012.FEMIG.Cliente
	ADD CONSTRAINT UQ_Cliente_email UNIQUE (email)
;

ALTER TABLE GD1C2012.FEMIG.Cliente
	ADD CONSTRAINT UQ_Cliente_telefono UNIQUE (telefono)
;

ALTER TABLE GD1C2012.FEMIG.Factura
	ADD CONSTRAINT UQ_Facturas_codFactura UNIQUE (codFactura)
;


--  Create Primary Key Constraints 
ALTER TABLE GD1C2012.FEMIG.Pantalla ADD CONSTRAINT PK_Pantalla 
	PRIMARY KEY CLUSTERED (pantallaID)
;

ALTER TABLE GD1C2012.FEMIG.Rol ADD CONSTRAINT PK_Roles 
	PRIMARY KEY CLUSTERED (rolID)
;

ALTER TABLE GD1C2012.FEMIG.RolPantalla ADD CONSTRAINT PK_RolesPantallas 
	PRIMARY KEY CLUSTERED (rolID, pantallaID)
;

ALTER TABLE GD1C2012.FEMIG.RolUsuario ADD CONSTRAINT PK_RolesUsuarios 
	PRIMARY KEY CLUSTERED (usuarioID, rolID)
;

ALTER TABLE GD1C2012.FEMIG.Usuario ADD CONSTRAINT PK_Usuarios 
	PRIMARY KEY CLUSTERED (usuarioID)
;
ALTER TABLE GD1C2012.FEMIG.Autos ADD CONSTRAINT PK_Auto 
	PRIMARY KEY CLUSTERED (patente)
;

ALTER TABLE GD1C2012.FEMIG.Chofer ADD CONSTRAINT PK_Chofer 
	PRIMARY KEY CLUSTERED (dniChofer)
;

ALTER TABLE GD1C2012.FEMIG.ChoferAutoTurno ADD CONSTRAINT PK_ChoferAutoTurno 
	PRIMARY KEY CLUSTERED (dniChofer, turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Cliente ADD CONSTRAINT PK_Cliente 
	PRIMARY KEY CLUSTERED (dniCliente)
;

ALTER TABLE GD1C2012.FEMIG.Factura ADD CONSTRAINT PK_Facturas 
	PRIMARY KEY CLUSTERED (codFactura)
;

ALTER TABLE GD1C2012.FEMIG.Reloj ADD CONSTRAINT PK_Reloj 
	PRIMARY KEY CLUSTERED (nroSerieReloj)
;

ALTER TABLE GD1C2012.FEMIG.Rendicion ADD CONSTRAINT PK_Rendicion 
	PRIMARY KEY CLUSTERED (fecha, dniChofer, turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Turno ADD CONSTRAINT PK_Turno 
	PRIMARY KEY CLUSTERED (turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Viaje ADD CONSTRAINT PK_Viaje 
	PRIMARY KEY CLUSTERED (viajeID)
;


--  Create Foreign Key Constraints 
ALTER TABLE GD1C2012.FEMIG.RolPantalla ADD CONSTRAINT FK_RolPantalla_Pantalla 
	FOREIGN KEY (pantallaID) REFERENCES GD1C2012.FEMIG.Pantalla (pantallaID)
;

ALTER TABLE GD1C2012.FEMIG.RolPantalla ADD CONSTRAINT FK_RolPantalla_Rol 
	FOREIGN KEY (rolID) REFERENCES GD1C2012.FEMIG.Rol (rolID)
;

ALTER TABLE GD1C2012.FEMIG.RolUsuario ADD CONSTRAINT FK_RolUsuario_Rol 
	FOREIGN KEY (rolID) REFERENCES GD1C2012.FEMIG.Rol (rolID)
;

ALTER TABLE GD1C2012.FEMIG.RolUsuario ADD CONSTRAINT FK_RolUsuario_Usuario 
	FOREIGN KEY (usuarioID) REFERENCES GD1C2012.FEMIG.Usuario (usuarioID)
;
ALTER TABLE GD1C2012.FEMIG.Autos ADD CONSTRAINT FK_Auto_Reloj 
	FOREIGN KEY (nroSerieReloj) REFERENCES GD1C2012.FEMIG.Reloj (nroSerieReloj)
;

ALTER TABLE GD1C2012.FEMIG.ChoferAutoTurno ADD CONSTRAINT FK_ChoferAutoTurno_Chofer 
	FOREIGN KEY (dniChofer) REFERENCES GD1C2012.FEMIG.Chofer (dniChofer)
;

ALTER TABLE GD1C2012.FEMIG.ChoferAutoTurno ADD CONSTRAINT FK_ChoferAutoTurno_Turno 
	FOREIGN KEY (turnoID) REFERENCES GD1C2012.FEMIG.Turno (turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Rendicion ADD CONSTRAINT FK_Rendicion_ChoferAutoTurno 
	FOREIGN KEY (dniChofer, turnoID) REFERENCES GD1C2012.FEMIG.ChoferAutoTurno (dniChofer, turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Viaje ADD CONSTRAINT FK_Viaje_ChoferAutoTurno 
	FOREIGN KEY (dniChofer, turnoID) REFERENCES GD1C2012.FEMIG.ChoferAutoTurno (dniChofer, turnoID)
;

ALTER TABLE GD1C2012.FEMIG.Viaje ADD CONSTRAINT FK_Viaje_Factura 
	FOREIGN KEY (codFactura) REFERENCES GD1C2012.FEMIG.Factura (codFactura)
;

ALTER TABLE GD1C2012.FEMIG.Viaje ADD CONSTRAINT FK_Viaje_Cliente 
	FOREIGN KEY (dniCliente) REFERENCES GD1C2012.FEMIG.Cliente (dniCliente)
;



EXEC sp_addextendedproperty 'MS_Description', '0: El rol está activo
1: El rol esta inhabilitado', 'Schema', FEMIG, 'table', Rol, 'column', anulado
;



EXEC sp_addextendedproperty 'MS_Description', '0 o null: no tiene acceso
1: tiene acceso', 'Schema', FEMIG, 'table', RolPantalla, 'column', acceso
;
