--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.3.932
--   Created On : martes, 05 junio, 2012 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 





--  Create Tables 
CREATE TABLE Auto ( 
	patente varchar(10) NOT NULL,
	marca varchar(255) NOT NULL,
	modelo varchar(255) NOT NULL,
	licencia varchar(26) NOT NULL,
	rodado varchar(10) NOT NULL,
	nroSerieReloj varchar(18) NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE Chofer ( 
	dniChofer numeric(18) NOT NULL,
	nombre varchar(255) NOT NULL,
	apellido varchar(255) NOT NULL,
	direccion varchar(255) NOT NULL,
	telefono numeric(18) NOT NULL,
	email varchar(50),
	fechaNacimiento datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE ChoferAutoTurno ( 
	fecha datetime NOT NULL,
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL,
	patente varchar(10)
)
;

CREATE TABLE Cliente ( 
	dniCliente numeric(18) NOT NULL,
	nombre varchar(255) NOT NULL,
	apellido varchar(255) NOT NULL,
	telefono numeric(18) NOT NULL,
	direccion varchar(255) NOT NULL,
	email varchar(255),
	fechaNacimiento datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE Factura ( 
	codFactura numeric(18) NOT NULL,
	fecha_inicio datetime NOT NULL,
	fecha_fin datetime NOT NULL,
	dniCliente numeric(18) NOT NULL,
	importe_total numeric(18) NOT NULL
)
;

CREATE TABLE Reloj ( 
	nroSerieReloj varchar(18) NOT NULL,
	marca varchar(255) NOT NULL,
	modelo varchar(255) NOT NULL,
	fechaVersion datetime NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE Rendicion ( 
	fecha datetime NOT NULL,
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL
)
;

CREATE TABLE Turno ( 
	turnoID varchar(20) NOT NULL,
	horaInicio numeric(18) NOT NULL,
	horaFin numeric(18) NOT NULL,
	descripcion varchar(255) NOT NULL,
	valorFicha numeric(18,2) NOT NULL,
	valorBandera numeric(18,2) NOT NULL,
	anulado varchar(1)
)
;

CREATE TABLE Viaje ( 
	viajeID numeric(18) NOT NULL,
	tipoViaje varchar(10) NOT NULL,
	cantFichas numeric(18) NOT NULL,
	fecha datetime NOT NULL,
	dniCliente numeric(18) NOT NULL,
	codFactura numeric(18),
	dniChofer numeric(18) NOT NULL,
	turnoID varchar(20) NOT NULL
)
;


--  Create Indexes 
ALTER TABLE Auto
	ADD CONSTRAINT UQ_Auto_licencia UNIQUE (licencia)
;

ALTER TABLE Auto
	ADD CONSTRAINT UQ_Auto_nroSerieReloj UNIQUE (nroSerieReloj)
;

ALTER TABLE Chofer
	ADD CONSTRAINT UQ_Chofer_email UNIQUE (email)
;

ALTER TABLE Cliente
	ADD CONSTRAINT UQ_Cliente_email UNIQUE (email)
;

ALTER TABLE Cliente
	ADD CONSTRAINT UQ_Cliente_telefono UNIQUE (telefono)
;

ALTER TABLE Factura
	ADD CONSTRAINT UQ_Facturas_codFactura UNIQUE (codFactura)
;

--  Create Primary Key Constraints 
ALTER TABLE Auto ADD CONSTRAINT PK_Auto 
	PRIMARY KEY CLUSTERED (patente)
;

ALTER TABLE Chofer ADD CONSTRAINT PK_Chofer 
	PRIMARY KEY CLUSTERED (dniChofer)
;

ALTER TABLE ChoferAutoTurno ADD CONSTRAINT PK_ChoferAutoTurno 
	PRIMARY KEY CLUSTERED (dniChofer, turnoID)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente 
	PRIMARY KEY CLUSTERED (dniCliente)
;

ALTER TABLE Factura ADD CONSTRAINT PK_Facturas 
	PRIMARY KEY CLUSTERED (codFactura)
;

ALTER TABLE Reloj ADD CONSTRAINT PK_Reloj 
	PRIMARY KEY CLUSTERED (nroSerieReloj)
;

ALTER TABLE Rendicion ADD CONSTRAINT PK_Rendicion 
	PRIMARY KEY CLUSTERED (fecha, dniChofer, turnoID)
;

ALTER TABLE Turno ADD CONSTRAINT PK_Turno 
	PRIMARY KEY CLUSTERED (turnoID)
;

ALTER TABLE Viaje ADD CONSTRAINT PK_Viaje 
	PRIMARY KEY CLUSTERED (viajeID)
;



--  Create Foreign Key Constraints 
ALTER TABLE Auto ADD CONSTRAINT FK_Auto_Reloj 
	FOREIGN KEY (nroSerieReloj) REFERENCES Reloj (nroSerieReloj)
;

ALTER TABLE ChoferAutoTurno ADD CONSTRAINT FK_ChoferAutoTurno_Chofer 
	FOREIGN KEY (dniChofer) REFERENCES Chofer (dniChofer)
;

ALTER TABLE ChoferAutoTurno ADD CONSTRAINT FK_ChoferAutoTurno_Turno 
	FOREIGN KEY (turnoID) REFERENCES Turno (turnoID)
;

ALTER TABLE Rendicion ADD CONSTRAINT FK_Rendicion_ChoferAutoTurno 
	FOREIGN KEY (dniChofer, turnoID) REFERENCES ChoferAutoTurno (dniChofer, turnoID)
;

ALTER TABLE Viaje ADD CONSTRAINT FK_Viaje_ChoferAutoTurno 
	FOREIGN KEY (dniChofer, turnoID) REFERENCES ChoferAutoTurno (dniChofer, turnoID)
;

ALTER TABLE Viaje ADD CONSTRAINT FK_Viaje_Factura 
	FOREIGN KEY (codFactura) REFERENCES Factura (codFactura)
;

ALTER TABLE Viaje ADD CONSTRAINT FK_Viaje_Cliente 
	FOREIGN KEY (dniCliente) REFERENCES Cliente (dniCliente)
;
